name: insight
description: "Insight: The app by the students, and for the students of Indian Institute of Science Education and Research, Mohali."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
